# Generated by Django 3.2.5 on 2022-06-12 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teams',
        ),
    ]
