# Generated by Django 3.2.5 on 2022-06-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
